name: Jest API Tests

on: [push]

jobs:
  jest-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          working-directory: ./api_jest_axios
      - name: Install modules
        run: npm install
        with:
          working-directory: ./api_jest_axios
      - name: Run tests
        run: npm run test
        with:
          working-directory: ./api_jest_axios
