name: Jest API Tests

on: [push]

jobs:
  jest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: npm install
        working-directory: ./api_jest_axios
      - name: Jest run
        run: npm run test
        working-directory: ./api_jest_axios
