name: Jest API Tests

on: [push]

jobs:
  jest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jest run
        uses: stefanoeb/jest-action@1.0.3
        with:
            working-directory: ./api_jest_axios
